export const SET_USER_EMAIL = "SET_USER_EMAIL";
export const SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN";
export const SET_VERIFY_EMAIL_ATTEMPTS = "SET_VERIFY_EMAIL_ATTEMPTS";
export const SET_FORGET_PASS_EMAIL_ATTEMPTS = "SET_FORGET_PASS_EMAIL_ATTEMPTS";
export const CLEAR_SESSION = "CLEAR_SESSION";
export const CLEAR_USER = "CLEAR_USER";
